### ISSUE TITLE
params361.m文件

### ISSUE THREAD

**Issue by wqfncwinciuwn** [Ssz990220/Time_Optimal_Trajectory_Control#1]
你好，我想向你请教一下这个文件里面的具体参数是干什么用的，有点没看懂这个文件，然后基于的这篇文章我也没找到Verdonck - Kuka361/cd3/TrajectCompensation/Studenten/Tekst PDF/

**Comment by Ssz990220** [comment]
您好，他提到的文章大概率是[这一篇](https://www.researchgate.net/publication/28360889_Contributions_to_Contact_Modeling_and_Identification_and_Optimal_Robot_Motion_Planning)，是作者的博士论文。
我印象中这个文件应该负责定义机器人模型（运动学、动力学、控制器），可以考虑结合代码进行理解。
作者原本的README文件在同目录下README.txt。

**Comment by wqfncwinciuwn** [comment]
> 您好，他提到的文章大概率是[这一篇](https://www.researchgate.net/publication/28360889_Contributions_to_Contact_Modeling_and_Identification_and_Optimal_Robot_Motion_Planning)，是作者的博士论文。 我印象中这个文件应该负责定义机器人模型（运动学、动力学、控制器），可以考虑结合代码进行理解。 作者原本的README文件在同目录下README.txt。

好的，我去学习一下，谢谢
