### ISSUE TITLE
params361.m文件

### ISSUE THREAD

**Issue by wqfncwinciuwn** [Ssz990220/Time_Optimal_Trajectory_Control#2]
您好，我把那篇博士论文看完了还是没明白这里面的参数具体是有什么作用，这个文件好像最后只需要得到taumax这个最大力矩参数对吗？是利用驱动器参数辨识出力矩吗？能不能请您详细得教一下

**Comment by Ssz990220** [comment]
您好，

依照我对这篇论文的印象，以及对于时间最优轨迹规划问题的理解，在轨迹规划过程中，一般只需要知道
1. 目标路径（不含时间参数）
2. 机械臂运动学参数
3. 机械臂动力学参数（如各个关节惯性张量，用于求解力矩）
4. 关节速度、加速度（可能有跃度约束）约束
5. 关节力矩约束

知道以上几点之后就可以实现对于时间最优轨迹速度规划的求解。

至于您提问的“是利用驱动器参数辨识出力矩吗”这个问题，我没有十分理解。
我的感觉是，在时间最优轨迹规划问题中，力矩是通过逆向动力学求解的（已知关节加速度、速度、位置求解力矩，当然，在问题求解的过程中速度是以参数化 $\dot{s}$ 的形式表示的，加速度同样）。而在正向动力学求解的过程中，机械臂的动力学参数（如惯性张量）是认定为已知的，诚然，在实际问题中，为了获得最高精度的动力学参数，需要动力学参数标定，但这不属于本问题的讨论范围。

希望能够回答您的问题。
如果您还有疑惑，可以考虑联系文章的原作者。
